name: Build and Push PG Exporter

on:
  push:
    branches:
      - main
    paths:
      - metrics/**
      - .github/workflows/build-and-push-exporter.yml

env:
  REGISTRY: ghcr.io
  EXPORTER_IMAGE_NAME: ${{ github.repository }}/pg-exporter

jobs:
  build-exporter:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata - PG Exporter
        id: meta-exporter
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.EXPORTER_IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha,format=short
            type=raw,value={{date 'YYYYMMDD'}}

      - name: Build and push - PG Exporter
        uses: docker/build-push-action@v5
        with:
          context: ./metrics
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta-exporter.outputs.tags }}
          labels: ${{ steps.meta-exporter.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
